config/routes.rb
#rails g resource Pokemon
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq" 

  resources :pokemons, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'pokemons/upload', to: 'pokemons#upload'
  post 'pokemons/destroy_all', to: 'pokemons#destroy_all'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
#rails g model Pokemon
class Pokemon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  def index
    @pokemons = Pokemon.all
  end

  def upload
    csv_path = File.join Rails.root, 'db', 'pokemon.csv'
    PokemonAddWorker.perform_async(csv_path)
    flash[:notice] = "Pokemons are being added to the database."
    redirect_to pokemons_path
  end

  def destroy_all
    PokemonRemoveWorker.perform_async
    flash[:notice] = "Pokemons are getting removed from the database."
    redirect_to pokemons_path
  end

end





def upload
  csv_path = File.join Rails.root, 'db', 'pokemon.csv'
  CSV.foreach((csv_path), headers: true) do |pokemon|
    Pokemon.create(
      pokedex_id: pokemon[0],
      name: pokemon[1],
      height: pokemon[3],
      weight: pokemon[4])
    end
    flash[:notice] = "All 807 Pokemons added to db."
    redirect_to pokemons_path
  end

  def destroy_all
    Pokemon.destroy_all
    flash[:notice] = "All 807 Pokemons deleted from db."
    redirect_to pokemons_path
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/index.erb
<h1>Pokemons</h1>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%#= link_to "See sidekiq stats", sidekiq_web_path %>

<%= form_tag pokemons_upload_path do %>
  <%= submit_tag "Import Pokemons" %>
<% end %>

<%= form_tag pokemons_destroy_all_path do %>
  <%= submit_tag "Delete Pokemons" %>
<% end %>

<table>
  <tr>
    <th>ID</th>
    <th>Pokemon</th>
    <th>Height</th>
    <th>Weight</th>
  </tr>
  <% @pokemons.each do |pokemon| %>
    <tr>
      <td><%=pokemon.pokedex_id%></td>
      <td><%=pokemon.name%></td>
      <td><%=pokemon.height%></td>
      <td><%=pokemon.weight%></td>
    </tr>
  <%end%>
</table>